env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-shadow:
   - error
   - builtinGlobals: true
     hoist: functions
  no-use-before-define:
   - error
   - functions: false
     classes: false
